name: ca
services:
  frontend:
    container_name: ca-frontend
    build:
      context: comment-analysis-frontend/.
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - VITE_ENV=prod
      - VITE_BACKEND_BASE_URL=http://localhost:8080/api/v1
      - VITE_GOOGLE_CLIENT_ID={VITE_GOOGLE_CLIENT_ID}
    depends_on:
      - backend

  backend:
    container_name: ca-backend
    build:
      context: comment-analysis/.
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILE_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/ca-app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    ports:
      - 8080:8080
    depends_on:
      - db
    
  db:
    container_name: ca-db
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_DB=ca-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  flyway-migration:
    container_name: ca-flyway-migration
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/ca-app -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./ca-app-db/:/flyway/sql
    depends_on:
      - db

  analysis-service:
    container_name: ca-analysis-service
    build:
      context: ./ca-service-analysis
    command: bash /app/scripts/run_service.sh
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ca-app
      - VLLM_HOST=10.0.2.6
      - VLLM_PORT=9000
      - PREFECT_API_URL=http://analysis-service-monitoring:4200/api
      - LOGURU_LEVEL=WARNING
    depends_on:
      # - analysis-service-monitoring
      - db

  db-monitor:
    container_name: ca-db-monitor
    build:
      context: ./ca-service-analysis
    command: streamlit run src/st_monitor.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "4001:8501"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ca-app
    depends_on:
      # - analysis-service-monitoring
      - db

  analysis-service-monitoring:
    container_name: ca-analysis-service-monitor
    build:
      context: ./ca-service-analysis
    command: bash /app/scripts/run_prefect.sh
    ports:
      - 4002:4200
    volumes:
      - prefect-data:/root/.prefect/
    healthcheck:
      test: curl --fail http://localhost:4200/api/health
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


volumes:
  pgdata:
    driver: local
  prefect-data:
